# Generated by Django 5.0.14 on 2026-06-20 05:21

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('cor', models.CharField(max_length=7)),
                ('rastreia_conclusao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraRecorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], max_length=8)),
                ('dias', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('ignorar_feriados', models.BooleanField(default=False)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regra de recorrência',
                'verbose_name_plural': 'Regras de recorrência',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('rastrear_conclusao', models.BooleanField()),
                ('status', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('REMARCADO', 'Remarcado')], max_length=10, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='planner.classe')),
                ('regra_recorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='planner.regrarecorrencia')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('inicio_override', models.DateTimeField(blank=True, null=True)),
                ('fim_override', models.DateTimeField(blank=True, null=True)),
                ('status_override', models.CharField(blank=True, max_length=10, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='planner.evento')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('esforco_estimado', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INBOX', 'Inbox'), ('PROMOVIDA', 'Promovida')], default='INBOX', max_length=10)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='planner.classe')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='origem_tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='planner.tarefa'),
        ),
        migrations.AddConstraint(
            model_name='ocorrencia',
            constraint=models.UniqueConstraint(fields=('evento', 'data'), name='uq_ocorrencia_evento_data'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['inicio', 'fim'], name='planner_eve_inicio_1e702b_idx'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(check=models.Q(('fim__gt', models.F('inicio'))), name='ck_evento_fim_apos_inicio'),
        ),
    ]
