# Generated by Django 5.0.14 on 2026-07-03 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_seed_classes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscolhaCenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("lote", models.JSONField()),
                ("escolhido", models.CharField(max_length=60)),
                ("era_sugerido", models.BooleanField()),
                ("pesos_no_momento", models.JSONField()),
            ],
            options={
                "verbose_name": "Escolha de cenário",
                "verbose_name_plural": "Escolhas de cenário",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="PesoPreferencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("metrica", models.CharField(max_length=40, unique=True)),
                ("valor", models.FloatField(default=1.0)),
            ],
            options={
                "verbose_name": "Peso de preferência",
                "verbose_name_plural": "Pesos de preferência",
            },
        ),
    ]
