# Generated by Django 5.0.14 on 2026-06-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_seed_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="origem_externa_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
