# Generated by Django 5.0.14 on 2026-07-03 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_escolhacenario_pesopreferencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroExecucao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("planejado_min", models.PositiveIntegerField(blank=True, null=True)),
                ("real_min", models.PositiveIntegerField(blank=True, null=True)),
                ("remarcado", models.BooleanField(default=False)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execucoes",
                        to="planner.classe",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execucoes",
                        to="planner.evento",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execucoes",
                        to="planner.tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de execução",
                "verbose_name_plural": "Registros de execução",
                "ordering": ["-criado_em"],
            },
        ),
    ]
