# Generated by Django 5.0.14 on 2026-07-04 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_registroexecucao"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeriadoLocal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120)),
                ("dia", models.PositiveSmallIntegerField()),
                ("mes", models.PositiveSmallIntegerField()),
                ("ano", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Feriado local",
                "verbose_name_plural": "Feriados locais",
                "ordering": ["mes", "dia"],
            },
        ),
        migrations.AddConstraint(
            model_name="feriadolocal",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("dia__gte", 1), ("dia__lte", 31), ("mes__gte", 1), ("mes__lte", 12)
                ),
                name="ck_feriadolocal_data_valida",
            ),
        ),
        migrations.AddConstraint(
            model_name="feriadolocal",
            constraint=models.UniqueConstraint(
                fields=("dia", "mes", "ano"), name="uq_feriadolocal_data"
            ),
        ),
    ]
