# Generated by Django 5.0.14 on 2026-08-15 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_dono_obrigatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="dias_permitidos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="estrategia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CEDO", "O quanto antes"),
                    ("TARDE", "O mais perto possível do prazo"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="janela_fim",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="janela_inicio",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="nao_antes_de",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="nao_depois_de",
            field=models.DateField(blank=True, null=True),
        ),
    ]
