# Generated by Django 5.0.14 on 2026-08-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0010_tarefa_dias_permitidos_tarefa_estrategia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="classe_override",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrencias_override",
                to="planner.classe",
            ),
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="descricao_override",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="titulo_override",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
