# Generated by Django 5.0.14 on 2026-08-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0011_conteudo_por_ocorrencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="chave_importacao",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="evento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chave_importacao", ""), _negated=True),
                fields=("dono", "chave_importacao"),
                name="uq_evento_dono_chave_importacao",
            ),
        ),
    ]
